### ISSUE TITLE
App does not work.

### ISSUE THREAD

**Issue by seriousabin** [devapro/LANwalkieTalkie#1]
I downloaded the latest release version 0.0.2as available here.

For some odd reason the walkie talkie does not function at all.
The app does open but when i clicked 'messages' it does not open anything or foes anything.
The same goes for 'settings' too.Only the 'exit' works.
The big voice button does nothing either.I opened wifi and bluetooth still nothing.Did a bunch of restarts for the app nothing at all happens.

I am on Realme 6(Android 10 RealmeUI)
Note: No battery saver activated.

**Comment by devapro** [comment]
The app can work only in the LAN network. For the test, you should use two devices with the launched app in the same local network. After connect, you can push the voice button.
